Feature: api gateway
yandex-cloud/serverless-plugin pull request #62
Opened 2022-05-09 18:09 UTC by nikolaymatrosov

Initial support of API Gateway.
Currently, it lacks creating custom domains as there is no this feature in the public Cloud API.
Further improvements:
— add support for creating custom API Gateway integrations.
— add custom domain support.

2022-05-09 18:17 UTC, nikolaymatrosov commented
Should fix #8

2022-05-12 08:56 UTC, DavyJohnes requested changes

2022-05-12 08:56 UTC, DavyJohnes commented on package.json
> +    "openapi-types": "^11.0.0",
Это разве не devDevepency?

2022-05-12 08:56 UTC, DavyJohnes commented on package.json
> +  "jest": {
У нас же есть `config/jest.ts`, почему туда бы это не внести?

2022-05-12 08:56 UTC, DavyJohnes commented on package.json
> +      "server/**/*.{ts,tsx}"
🤔 это где такая директория? Не вижу ее ни в мастере ни в твоем ПР.

2022-05-12 08:56 UTC, DavyJohnes commented on package.json
> +    "transform": {
В конфиге уже определен `preset: ts-jest`, который включает в себя эту конфигурацию.

2022-05-12 08:56 UTC, DavyJohnes commented on src/deploy/deploy.test.ts
> +jest.mock('../utils/logging', () => ({
А зачем? Если хотим чтобы во время тестов не сыпали лишние логи, то может просто при запуске тестов сделаем `LOG_LEVEL=fatal`?

2022-05-12 08:56 UTC, DavyJohnes commented on src/deploy/deploy.ts
> +        await Promise.all(Object.values(this.triggerRegistry).map((trigger) => trigger.sync()));
Не очень понял, чем это отличается от того что было раньше? Это для того, чтобы синк элементов был параллельно а не последовательно? Если так, то почему ты и все остальные ресурсы не запараллелить?

2022-05-12 08:56 UTC, DavyJohnes commented on src/deploy/deploy.ts
> +        const providerConfig: ProviderConfig | undefined = this.serverless.service.provider as any;
Тут бы комментарий, зачем этот `any`?

2022-05-12 08:56 UTC, DavyJohnes commented on src/entities/api-gateway.ts
> +    openapiSpec?: string;
Это в каком состоянии у гейтвея может не быть спеки? Это ж неотъемлемый атрибут гейтвея?

2022-05-12 08:56 UTC, DavyJohnes commented on src/entities/api-gateway.ts
> +            ${requestParams.name}`);
Давай одной строкой? Я стараюсь везде избавлять от этого ступенчатого стиля :)

2022-05-12 08:56 UTC, DavyJohnes commented on src/entities/container-registry.ts
> -        try {
А почему ошибку теперь не обрабатываем?

2022-05-12 08:56 UTC, DavyJohnes commented on src/entities/function.ts
> +    toPathItemObject<T>(event: Event): [string, YcPathItemObject<T>] | undefined {
Спорно конечно, но мне кажется это по смыслу не методы сущности `Function`, ведь это специфично для гейтвея и OpenAPI, а значит где-то в районе тех сущностей и должно быть.

2022-05-12 08:56 UTC, DavyJohnes commented on src/utils/logging.ts
> +// @ts-ignore
Там тайпингов нет?

2022-05-12 09:42 UTC, nikolaymatrosov commented on src/utils/logging.ts
> +// @ts-ignore
нет( https://github.com/serverless/utils/issues/166

2022-05-12 09:56 UTC, nikolaymatrosov commented on src/entities/container-registry.ts
> -        try {
Потому что если мы тут ее поймаем и напечатаем, то кажется завершим деплой успешно. Я хотел выходить с ошибкой. Чтобы потом это можно было использовать в скриптах и шагах в CI/CD, чтобы они падали.

2022-05-12 09:56 UTC, nikolaymatrosov commented on src/entities/api-gateway.ts
> +    openapiSpec?: string;
Когда он еще не создан. Но возможно и правда его надо сразу в конструкторе создавать.

2022-05-12 09:56 UTC, nikolaymatrosov commented on src/deploy/deploy.ts
> +        const providerConfig: ProviderConfig | undefined = this.serverless.service.provider as any;
Тут нам бы отказаться от AWS тайпингов и написать полностью свои соответсвующие нашему конфигу.

2022-05-12 09:56 UTC, nikolaymatrosov commented on src/deploy/deploy.ts
> +        await Promise.all(Object.values(this.triggerRegistry).map((trigger) => trigger.sync()));
Да, эксперимент не довел до конца. Надо только проверить, что не упремся в ограничения на количество параллельных оперций у сервисов. Если такие есть где-то кроме компьюта.

2022-05-12 09:56 UTC, nikolaymatrosov commented on src/deploy/deploy.test.ts
> +jest.mock('../utils/logging', () => ({
Тут возможно и не нужно. В каком-то из тестов есть ассерты на то что мы в логе выводим.

2022-05-12 09:56 UTC, nikolaymatrosov commented on package.json
> +      "server/**/*.{ts,tsx}"
Упс. Копипаста

2022-05-31 14:18 UTC, DavyJohnes reviewed
Хотелось бы решить вопрос с моканием логгера в тестах, в остально все ок!

2022-05-31 14:18 UTC, DavyJohnes commented on src/deploy/deploy.test.ts
> +jest.mock('../utils/logging', () => ({
Ну это не объясняет почему мы во всех тестах стабаем логгирование) Надо придумать как-то более изящно это проверить, например перед начало конкретного теста установить уровен логгирования в `FATAL`.

2022-05-31 14:18 UTC, DavyJohnes commented on src/entities/api-gateway.ts
> +    openapiSpec?: string;
А что тут в итоге? Не получилось обязательным свойством сделать?

2022-05-31 14:20 UTC, DavyJohnes commented on src/types/serverless.ts
> +declare namespace Serverless {
А давай тут коммент напишем, ради чего мы оверрайдим тайпинги `Serverless`?

2022-06-15 16:08 UTC, nikolaymatrosov commented
> Хотелось бы решить вопрос с моканием логгера в тестах, в остально все ок!

Исправил.  Оставил только в том тесте, где реально проверяется вывод в консоль.

Остальные замечания тоже поправил. И добавил пару тестов на новую функциональность.

2022-06-20 08:50 UTC, DavyJohnes approved these changes

2022-06-20 08:50 UTC, DavyJohnes commented on src/types/serverless.ts
> +// Unfortunately, Serverless typings are handwritten and do not fully reflect Serverless complexity.
В идеале бы конечно в тайпинги законтрибьютить ;)

2022-06-20 08:51 UTC, merged